
[env]
TERM = "xterm-256color"


[window]
opacity = 0.75
#blur = true
startup_mode = "Maximized"

[font]
size = 20
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }

