theme = "gruber-darker"

[editor]
line-number = "relative"
mouse = true

[editor.auto-save]
after-delay = { enable = true, timeout = 1500 }

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w"
space = { b = ":new", x = ":buffer-close", v = ":vsplit-new", h = ":hsplit-new" }
S-l = ":buffer-next"
S-h = ":buffer-previous"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-h = "jump_view_left"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
