theme = "gruber-darker"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w"
space = { b = ":new", x = ":buffer-close" }
S-l = ":buffer-next"
S-h = ":buffer-previous"
C-v = ":vsplit-new"
C-h = ":hsplit-new"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
